toolbox:
- name: 日常
  tools:
  - name: 知乎
    description: 资料信息
    url: https://www.zhihu.com/
  - name: github/jacoovan
    description: 我的
    url: https://github.com/jacoovan
- name: 搜索
  tools:
  - name: google
    description: 搜索引擎
    url: https://www.google.com/