version: "3.8"

services:
  toolbox:
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    container_name: "${SERVICE_NAME}"
    stdin_open: true
    tty: true
    ports:
     - "${PORT_WEB}:80"
    restart: always
    volumes:
      - "../../config:/app/config:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  default:
    name: "toolbox"

